Repository FE-feed-meow/DidYouFeedMeow, pull requests merged in 2022-12, with the labels that each got.

#197 :lipstick: Modify : 이미지 css 수정
  src/components/modal/catInfoModal/style.ts
  src/pages/catListPage/style.ts
Labels: style

#198 :lipstick: Style: 고양이 상세페이지 UI 변경
  src/components/catInfo/style.ts
  src/pages/catInfoPage/CatInfoPage.tsx
  src/pages/catInfoPage/style.ts
Labels: style

#202 :bug: Modify : 모달 닫기 버튼 수정 & 주소 인풋창 글자제한 추가
  src/components/catInfo/style.ts
  src/components/modal/catInfoModal/CatInfoModal.tsx
  src/components/modal/catInfoModal/style.ts
  src/components/modal/mapModal/MapModal.tsx
  src/pages/catListPage/style.ts
  src/pages/recordMapPage/RecordMapPage.tsx
  src/pages/registerCatPage/RegisterCatPage.tsx
Labels: bug, style

#204 :bug: Modify: 냥이 정보 수정시 특이사항 적용안됨
  src/components/catInfo/CatInfo.tsx
  src/pages/registerCatPage/RegisterCatPage.tsx
Labels: bug

#200 :truck: Add: Router 폴더 추가, route.tsx 파일 이동
  src/Router/Route.tsx
  src/app/App.tsx
Labels: etc

#206 :art: Modify : style.ts 파일 분기
  src/atoms/button/Button.tsx
  src/atoms/button/style.ts
  src/atoms/dropdown/DropDown.tsx
  src/atoms/image/Image.tsx
  src/atoms/image/style.ts
  src/atoms/inputs/Inputs.tsx
  src/atoms/inputs/style.ts
  src/components/catFeedNone/CatFeedNone.tsx
  src/components/catFeedNone/style.ts
  src/components/catNewsItem/CatNewItem.tsx
  src/components/catNewsItem/style.ts
  src/components/joinQuizPage/style.ts
  src/pages/catInfoPage/style.ts
  src/pages/catNewsPage/CatNewsPage.tsx
  src/pages/catNewsPage/style.ts
  src/pages/errorPage/ErrorPage.tsx
  src/pages/errorPage/style.ts
  src/pages/joinPage/style.ts
  src/pages/profileEditPage/ProfileEditPage.tsx
  src/pages/profilePage/ProfilePage.tsx
  src/pages/splashPage/Splash.tsx
  src/pages/splashPage/style.ts
Labels: etc

#208 :lipstick: Modify : 밥등록시 밥정보가 없으면 저장할수 없음
  src/components/catFeed/CatFeed.tsx
  src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
  src/components/modal/catFoodPageModal/style.ts
Labels: bug, component, feature

#209 :bento: Style : 리드미 이미지 추가
  public/assets/images/readme.png
  public/assets/images/readme_button.png
Labels: set

#211 :bento: Style : 리드미 이미지 변경
  public/assets/images/readme.png
  public/assets/images/readme_button.png
Labels: set

#213 :sparkles: Feat : 로그인 상태에서 모바일 튜토리얼 하루만 보기
  src/components/tutorial/appTutorial/AppTutorial.tsx
  src/pages/recordMapPage/RecordMapPage.tsx
Labels: feature

#216 :adhesive_bandage: Add: 냥이정보페이지, 밥정보 ir기법 추가
  src/components/catFeed/CatFeed.tsx
  src/components/catInfo/CatInfo.tsx
Labels: feature
