Repository FE-feed-meow/DidYouFeedMeow, pull requests merged in 2022-10, with the labels that each got.

#1 :lipstick: Style : reset, root color, globalstyles 추가
  src/app/App.tsx
  src/app/style.ts
Labels: style

#2 :truck: Modify : index.tsx 경로 수정
  src/index.tsx
Labels: feature

#3 :art: Set : 폴더 구조 정리
  src/atoms/button/Button.tsx
  src/atoms/button/style.ts
  src/atoms/icon/Icon.tsx
  src/atoms/icon/style.ts
  src/atoms/image/Image.tsx
  src/atoms/image/style.ts
  src/atoms/input/Input.tsx
  src/atoms/input/style.ts
  src/components/catInfo/CatInfo.tsx
  src/components/catInfo/style.ts
  src/components/home/Home.tsx
  src/components/home/style.ts
  src/components/join/Join.tsx
  src/components/join/style.ts
  src/components/letterBox/LetterBox.tsx
  src/components/letterBox/style.ts
  src/components/login/Login.tsx
  src/components/login/style.ts
  src/components/modal/Modal.tsx
  src/components/modal/style.ts
  src/components/searchInpBox/SearchInpBox.tsx
  src/components/searchInpBox/style.ts
  src/components/sideBar/SideBar.tsx
  src/components/sideBar/style.ts
  src/pages/catInfoEditPage/CatinfoEditPage.tsx
  src/pages/catInfoEditPage/style.ts
  src/pages/catInfoPage/CatInfoPage.tsx
  src/pages/catInfoPage/style.ts
  src/pages/catLetterPage/CatLetterPage.tsx
  src/pages/catLetterPage/style.ts
  src/pages/catNewsPage/CatNewsPage.tsx
  src/pages/catNewsPage/style.ts
  src/pages/joinPage/JoinPage.tsx
  src/pages/joinPage/style.ts
  src/pages/joinQuizPage/JoinQuizPage.tsx
  src/pages/joinQuizPage/style.ts
  src/pages/loginPage/LoginPage.tsx
  src/pages/loginPage/style.ts
  src/pages/profileEditPage/ProfileEditPage.tsx
  src/pages/profileEditPage/style.ts
  src/pages/profilePage/ProfilePage.tsx
  src/pages/profilePage/style.ts
  src/pages/recordMapPage/RecordMapPage.tsx
  src/pages/recordMapPage/style.ts
  src/pages/registerCatPage/RegisterCatPage.tsx
  src/pages/registerCatPage/style.ts
  src/pages/splashPage/Splash.tsx
  src/pages/splashPage/style.ts
Labels: etc

#4 :sparkles: Feat: 버튼 아톰 구현
  src/atoms/button/Button.tsx
Labels: element, style

#7 :sparkles: Feat: 로그인 페이지 마크업 구현
  package-lock.json
  src/atoms/button/Button.tsx
  src/atoms/image/Image.tsx
  src/atoms/input/Input.tsx
  src/atoms/input/style.ts
  src/atoms/inputs/Inputs.tsx
  src/font.css
  src/pages/loginPage/LoginPage.tsx
Labels: page, style

#8 :sparkles: Feat: 회원가입페이지 마크업 구현
  src/pages/joinPage/JoinPage.tsx
  src/pages/loginPage/LoginPage.tsx
Labels: page, style

#10 :sparkles: Feat: 프로필페이지 마크업 구현
  public/assets/images/add-profile.svg
  src/app/style.ts
  src/atoms/image/Image.tsx
  src/atoms/inputs/Inputs.tsx
  src/components/join/Join.tsx
  src/components/join/style.ts
  src/components/login/Login.tsx
  src/components/login/style.ts
  src/pages/loginPage/LoginPage.tsx
  src/pages/profilePage/ProfilePage.tsx
Labels: page, style

#11 :sparkles: Feat: 퀴즈 리스트 컴포넌트, 퀴즈 페이지 마크업 구현
  src/atoms/button/Button.tsx
  src/components/quizList/QuizList.tsx
  src/components/quizList/style.ts
  src/pages/joinQuizPage/JoinQuizPage.tsx
  src/pages/profilePage/ProfilePage.tsx
Labels: component, page, style

#17 :sparkles: Feat : 장소,주소 검색페이지 마크업 구현
  public/assets/icons/icon-menu.svg
  src/components/searchInpBox/SearchInpBox.tsx
  src/pages/recordMapPage/RecordMapPage.tsx
Labels: feature

#24 Feat/삭제모달마크업구현
  src/components/modal/deleteModal/DeleteModal.tsx
  src/components/modal/deleteModal/style.ts
Labels: feature, style

#25 :sparkles: Feat : 취소 버튼 생성
  src/atoms/button/closeBtn/CloseBtn.tsx
  src/atoms/button/closeBtn/style.ts
Labels: feature

#29 ✨Feat : 냥이 등록페이지 마크업 구현
  public/assets/icons/icon-plus-small.svg
  public/assets/images/add-cat.svg
  src/atoms/button/Button.tsx
  src/pages/registerCatPage/RegisterCatPage.tsx
Labels: feature, page

#31 ✨Feat : 냥이 정보 상세 페이지 마크업 구현
  src/atoms/icon/Icon.tsx
  src/components/catFeed/CatFeed.tsx
  src/components/catFeed/feedCard/FeedCard.tsx
  src/components/catFeed/feedCard/style.ts
  src/components/catFeed/style.ts
  src/components/catInfo/CatInfo.tsx
  src/pages/catInfoPage/CatInfoPage.tsx
Labels: component, page

#33 Feat/고양이상세페이지모달생성
  src/components/modal/catModal/CatModal.tsx
  src/components/modal/catModal/style.ts
  src/components/modal/deleteModal/style.ts
Labels: feature, style

#35 :sparkles: Feat : 이용약관 모달 생성
  src/components/modal/termsModal/TermsModal.tsx
  src/components/modal/termsModal/style.ts
Labels: feature, style

#39 :lipstick: Modify : 삭제 모달 에러 코드 수정
  src/components/modal/deleteModal/DeleteModal.tsx
  src/components/modal/deleteModal/style.ts
Labels: bug, feature

#43 :sparkles: Feat: 스플래시 페이지 마크업 구현
  src/pages/splashPage/Splash.tsx
  src/pages/splashPage/style.ts
Labels: page, style

#42 :lipstick: Modify : 양옆 padding 값 40px로 수정 #41
  src/components/menuBoard/MenuBoard.tsx
  src/components/modal/mapModal/MapModal.tsx
  src/components/searchInpBox/SearchInpBox.tsx
Labels: feature, style

#40 :sparkles: Feat : 밥주기 모달 마크업 생성
  src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
  src/components/modal/catFoodPageModal/style.ts
  src/components/modal/style.ts
Labels: feature, style

#44 :sparkles: Feat: 404 페이지 마크업 구현
  public/assets/icons/icon-error.svg
  src/pages/errorPage/ErrorPage.tsx
  src/pages/errorPage/style.ts
Labels: page, style

#47 :sparkles: Feat : select박스 제거 후 input 생성, 현재시간 버튼 생성
  src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
  src/components/modal/catFoodPageModal/style.ts
Labels: feature, style

#49 :lipstick: Modify : style.ts 파일 분기
  src/components/menuBoard/MenuBoard.tsx
  src/components/menuBoard/style.ts
  src/components/modal/Modal.tsx
  src/components/modal/mapModal/MapModal.tsx
  src/components/modal/mapModal/style.ts
  src/components/searchInpBox/SearchInpBox.tsx
  src/components/searchInpBox/style.ts
  src/components/sideBar/SideBar.tsx
  src/components/sideBar/style.ts
Labels: etc

#52 💄 Modify : 아이콘 아톰 삭제 및 변경
  src/atoms/icon/Icon.tsx
  src/atoms/icon/style.ts
  src/components/catFeed/feedCard/FeedCard.tsx
  src/components/catInfo/CatInfo.tsx
  src/pages/catInfoPage/CatInfoPage.tsx
Labels: style

#53 Feat/모달과모달연결
  src/components/modal/catModal/CatModal.tsx
  src/components/modal/catModal/style.ts
  src/components/modal/deleteModal/style.ts
Labels: feature, style

#55 :sparkles: Feat : 고양이 정보 삭제 모달 연결
  src/atoms/button/closeBtn/CloseBtn.tsx
  src/components/catInfo/CatInfo.tsx
  src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
  src/components/modal/catModal/CatModal.tsx
  src/components/modal/deleteModal/DeleteModal.tsx
  src/components/modal/deleteModal/style.ts
  src/components/modal/termsModal/TermsModal.tsx
Labels: feature

#58 :sparkles: Feat: 라우터 설정, privateRoute 추가
  src/Route.tsx
  src/app/App.tsx
Labels: component, feature, page

#57 :sparkles: Feat : 고양이 밥 정보 삭제 모달 연결
  src/components/catFeed/feedCard/FeedCard.tsx
Labels: feature

#60 :sparkles: Feat : 메뉴 버튼 클릭시 게시판 모달 열기
  src/components/menuBoard/MenuBoard.tsx
  src/components/menuBoard/style.ts
  src/components/searchInpBox/SearchInpBox.tsx
  src/components/searchInpBox/style.ts
  src/pages/recordMapPage/RecordMapPage.tsx
Labels: feature

#62 :sparkles: Feat : 드롭박스 아톰 구현
  src/atoms/ dropdown/DropDown.tsx
  src/atoms/ dropdown/style.ts
Labels: feature, style

#66 :sparkles: Modify : 게시판 모달창 수정
  src/components/menuBoard/MenuBoard.tsx
  src/components/menuBoard/style.ts
  src/pages/recordMapPage/RecordMapPage.tsx
  src/pages/recordMapPage/style.ts
Labels: feature

#68 💄Modify: dropdown 넓이 props 스타일컴포넌트 타입 지정 및 파일 공백제거
  src/atoms/dropdown/DropDown.tsx
  src/atoms/dropdown/style.ts
Labels: bug, element, etc

#70 :sparkles: Feat : 고양이 상세 페이지에 밥주기 모달 연결
  src/pages/catInfoPage/CatInfoPage.tsx
Labels: feature

#77 :sparkles: Feat : 카카오맵 API 연결 및 홈 화면에 현위치 표시하기
  .prettierrc
  package-lock.json
  package.json
  public/index.html
  src/pages/recordMapPage/MyLocation.tsx
  src/pages/recordMapPage/RecordMapPage.tsx
  src/pages/recordMapPage/style.ts
  tsconfig.json
Labels: feature

#81 ✨ Feat: 로컬 고양이사진등록 및 헤더,이미지 컴포넌트 기능추가
  src/atoms/image/Image.tsx
  src/components/header/Header.tsx
  src/components/header/style.ts
  src/pages/registerCatPage/RegisterCatPage.tsx
  src/pages/registerCatPage/style.ts
Labels: component, feature

#80 :sparkles: Feat: Craco 설치 및 세팅
  craco.config.js
  package-lock.json
  package.json
  src/constants/index.ts
  tsconfig.extend.json
  tsconfig.json
Labels: feature, set

#82 :bug: Modify: package-lock.json conflict 해결
  package-lock.json
Labels: bug

#84 :sparkles: Feat : 고양이 밥 버튼들 클릭시 이미지 변화
  src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
  src/components/modal/catFoodPageModal/style.ts
Labels: feature

#86 :lipstick: Modify : 밥주기 페이지에서 이미지 클릭시 배경색 변경
  src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
  src/components/modal/catFoodPageModal/style.ts
Labels: feature

#89 :sparkles: Feat : 404 페이지 기능 구현
  src/pages/errorPage/ErrorPage.tsx
Labels: feature, page

#88 ✨ Add 드롭다운 요소 선택 및 밀림 해결
  src/atoms/button/Button.tsx
  src/atoms/dropdown/DropDown.tsx
  src/atoms/dropdown/style.ts
  src/components/header/Header.tsx
  src/pages/registerCatPage/RegisterCatPage.tsx
  src/pages/registerCatPage/style.ts
Labels: bug, feature, style

#93 :sparkles: Feat : 현재시간 기능 구현
  src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
  src/components/modal/catFoodPageModal/style.ts
Labels: feature

#95 :sparkles: Feat : 지도 검색기능 구현
  src/components/mapTemplate/MapTemplate.tsx
  src/components/mapTemplate/style.ts
  src/components/searchInpBox/SearchInpBox.tsx
  src/components/searchInpBox/style.ts
  src/pages/recordMapPage/RecordMapPage.tsx
  src/pages/recordMapPage/style.ts
Labels: feature
