Repository FE-feed-meow/DidYouFeedMeow, pull requests merged in 2022-11, with the labels that each got.

#97 :sparkles: Feat : 시간 설정 수정, 현재시간 버튼 삭제
  src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
  src/components/modal/catFoodPageModal/style.ts
Labels: feature

#99 💄Style: 냥이등록페이지 주소창추가
  src/atoms/dropdown/style.ts
  src/pages/registerCatPage/RegisterCatPage.tsx
  src/pages/registerCatPage/style.ts
Labels: style

#101 :sparkles: Feat : 밥주기 페이지에 감귤마켓 댓글 api연결
  src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
Labels: feature

#104 :sparkles: Feat : 고양이 밥 정보 리스트를 상세페이지에 보여주기
  src/components/catFeed/CatFeed.tsx
  src/components/catFeed/feedCard/FeedCard.tsx
  src/pages/catInfoPage/CatInfoPage.tsx
Labels: feature

#106 :sparkles: Feat : 냥이 등록 페이지에 입력한 주소 넘겨주기
  src/components/modal/mapModal/MapModal.tsx
  src/pages/recordMapPage/RecordMapPage.tsx
  src/pages/registerCatPage/RegisterCatPage.tsx
Labels: feature

#108 :lipstick: Style: 밥주기 스크롤 구현
  src/components/catFeed/CatFeed.tsx
  src/components/catFeed/feedCard/FeedCard.tsx
Labels: style

#109 ✨ Feat: 냥등록api 등록 후 페이지 이동 및 스타일 수정
  src/atoms/button/Button.tsx
  src/atoms/dropdown/DropDown.tsx
  src/pages/registerCatPage/RegisterCatPage.tsx
  src/pages/registerCatPage/style.ts
Labels: feature, page, style

#111 :sparkles: Feat : 밥 정보에 삭제 api 연결
  src/components/catFeed/feedCard/FeedCard.tsx
  src/components/catInfo/CatInfo.tsx
  src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
  src/components/modal/deleteModal/DeleteModal.tsx
  src/pages/catInfoPage/CatInfoPage.tsx
Labels: feature

#113 :sparkles: Feat : 현위치 버튼 추가
  public/assets/icons/icon-reset-location.svg
  public/index.html
  src/components/resetLocation/ResetLocation.tsx
  src/components/resetLocation/style.ts
  src/components/searchInpBox/SearchInpBox.tsx
  src/pages/recordMapPage/RecordMapPage.tsx
  src/pages/recordMapPage/style.ts
Labels: feature

#115 :lipstick: Modify : 괄호 위치 변경
  src/components/catFeed/feedCard/FeedCard.tsx
  src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
Labels: component

#117 ✨ Feat: 냥이 유효성 검사 및 냥이 상세페이지에 데이터 뿌리기
  src/app/App.tsx
  src/atoms/inputs/Inputs.tsx
  src/components/catInfo/CatInfo.tsx
  src/components/catInfo/style.ts
  src/pages/registerCatPage/RegisterCatPage.tsx
Labels: feature, page

#119 :sparkles: Feat : 밥정보 날짜별 분류
  src/components/catFeed/CatFeed.tsx
  src/components/catFeed/feedCard/FeedCard.tsx
  src/components/header/Header.tsx
Labels: feature

#121 ✨ Modify: 엑박해결
  src/components/catInfo/CatInfo.tsx
  src/components/catInfo/style.ts
  src/pages/catInfoPage/CatInfoPage.tsx
  src/pages/registerCatPage/RegisterCatPage.tsx
  src/styles/commonStyle.ts
Labels: bug, style

#123 ✨ Feat/냥이등록게시물api로변경
  src/components/catFeed/CatFeed.tsx
  src/components/catFeed/feedCard/FeedCard.tsx
  src/components/catFeed/feedCard/style.ts
  src/components/catFeed/style.ts
  src/components/catInfo/CatInfo.tsx
  src/components/catInfo/style.ts
  src/pages/catInfoPage/style.ts
  src/pages/registerCatPage/RegisterCatPage.tsx
Labels: feature, page

#125 :lipstick: Modify : 밥 날짜 정보 수정, 오늘 날짜의 정보만 나오게 함
  src/components/catFeed/CatFeed.tsx
Labels: feature

#127 Modify : api 수정
  src/components/catFeed/CatFeed.tsx
  src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
  src/components/modal/deleteModal/DeleteModal.tsx
  src/pages/catInfoPage/CatInfoPage.tsx
Labels: feature

#130 :sparkles: 삭제 api 등록
  src/components/modal/deleteModal/DeleteModal.tsx
Labels: feature

#133 :sparkles: Feat : 스플래시 페이지 기능 구현
  src/pages/splashPage/Splash.tsx
Labels: feature, page

#135 :bug: Modify: 버튼 props 추가
  src/atoms/button/Button.tsx
  src/pages/catInfoPage/CatInfoPage.tsx
  src/pages/registerCatPage/RegisterCatPage.tsx
Labels: bug

#137 :sparkles: Feat : 내가 등록한 냥이 보기
  public/assets/icons/icon-reset-location.svg
  public/index.html
  src/app/App.tsx
  src/components/catList/CatList.tsx
  src/components/catList/style.ts
  src/components/menuBoard/MenuBoard.tsx
  src/components/menuBoard/style.ts
  src/components/resetLocation/ResetLocation.tsx
  src/components/resetLocation/style.ts
  src/components/searchInpBox/SearchInpBox.tsx
  src/components/searchInpBox/style.ts
  src/pages/recordMapPage/RecordMapPage.tsx
Labels: feature

#139 :sparkles: Feat : 밥정보 없을 때 꼬르륵 페이지가 나오도록 만듬
  src/components/catFeedNone/CatFeedNone.tsx
  src/components/catFeedNone/style.ts
  src/pages/catInfoPage/CatInfoPage.tsx
Labels: feature

#143 Feat/logout
  src/components/menuBoard/MenuBoard.tsx
  src/components/menuBoard/style.ts
Labels: component, feature

#147 :sparkles: Feat : 본인이 작성한 밥 정보만 삭제 가능
  src/components/catFeed/CatFeed.tsx
  src/components/catFeed/feedCard/FeedCard.tsx
Labels: feature

#151 :sparkles: Feat : 밥줬냥 신문 마크업
  src/app/App.tsx
  src/components/catNewsItem/CatNewItem.tsx
  src/pages/catNewsPage/CatNewsPage.tsx
Labels: feature

#153 :sparkles: Add: 수정기능 추가
  src/app/App.tsx
  src/atoms/dropdown/DropDown.tsx
  src/components/catInfo/CatInfo.tsx
  src/pages/catInfoEditPage/CatinfoEditPage.tsx
  src/pages/registerCatPage/RegisterCatPage.tsx
  src/pages/registerCatPage/style.ts
Labels: feature, page

#155 :sparkles: Feat : 헤더에 홈 버튼 추가
  public/assets/images/home.svg
  src/components/header/Header.tsx
  src/components/header/style.ts
  src/pages/joinQuizPage/JoinQuizPage.tsx
Labels: feature

#157 :sparkles: Feat : 동네 냥 소식통 페이지 추가
  public/assets/icons/icon-reset-location.svg
  public/assets/images/cat-face.svg
  public/assets/images/cat-sample-img.jpeg
  public/assets/images/cat-sample-img2.jpeg
  src/app/App.tsx
  src/components/catLettersItem/CatLettersItem.tsx
  src/components/catLettersItem/style.ts
  src/components/catList/CatList.tsx
  src/components/header/style.ts
  src/components/searchInpBox/style.ts
  src/pages/catLetterPage/CatLetterPage.tsx
  src/pages/catLetterPage/style.ts
  src/pages/recordMapPage/RecordMapPage.tsx
  src/styles/commonStyle.ts
Labels: feature

#159 :lipstick: Modify : 헤더 컴포넌트 홈 버튼 수정
  src/components/header/Header.tsx
  src/components/header/style.ts
  src/components/mapTemplate/style.ts
  src/pages/catNewsPage/CatNewsPage.tsx
Labels: style

#163 :sparkles: Feat : 등록한 냥이들 마커 찍기 & 마커에 냥이 모달 등록하기
  src/components/catList/CatList.tsx
  src/components/modal/catInfoModal/CatInfoModal.tsx
  src/components/modal/catInfoModal/style.ts
  src/pages/catLetterPage/CatLetterPage.tsx
  src/pages/recordMapPage/RecordMapPage.tsx
  src/pages/recordMapPage/style.ts
Labels: feature

#167 :sparkles: Modify : 냥이 모달 정보 수정
  src/components/catList/CatList.tsx
  src/components/mapTemplate/MapTemplate.tsx
  src/components/mapTemplate/style.ts
  src/components/modal/catInfoModal/CatInfoModal.tsx
  src/components/searchInpBox/SearchInpBox.tsx
  src/components/searchInpBox/style.ts
  src/pages/recordMapPage/RecordMapPage.tsx
Labels: feature

#169 :lipstick: Modify: 보더래디어스 수정 및 코드정리
  src/components/catInfo/style.ts
  src/pages/registerCatPage/RegisterCatPage.tsx
Labels: style

#173 ✨ Feat: 냥이 목록, 홈페이지 로딩 추가
  public/assets/images/loading.svg
  src/components/loading/Loading.tsx
  src/components/loading/style.ts
  src/pages/catListPage/CatListPage.tsx
  src/pages/recordMapPage/RecordMapPage.tsx
Labels: feature

#175 :sparkles: Feat : 전체화면 배경 이미지 적용 및 스타일 수정
  public/assets/images/main-background.png
  public/favicon.ico
  src/app/App.tsx
  src/components/catLettersItem/CatLettersItem.tsx
  src/components/catLettersItem/style.ts
  src/components/header/style.ts
  src/components/mapTemplate/style.ts
  src/components/menuBoard/style.ts
  src/components/modal/deleteModal/style.ts
  src/components/modal/mapModal/style.ts
  src/components/modal/style.ts
  src/components/searchInpBox/style.ts
  src/components/tutorial/style.ts
  src/pages/catInfoPage/CatInfoPage.tsx
  src/pages/catLetterPage/style.ts
  src/pages/catListPage/style.ts
  src/pages/loginPage/style.ts
  src/pages/recordMapPage/RecordMapPage.tsx
  src/pages/recordMapPage/style.ts
  src/styles/commonStyle.ts
Labels: feature, style

#179 :bug: Modify:냥이 수정 출생년도
  src/pages/registerCatPage/RegisterCatPage.tsx
Labels: bug

#181 :sparkles: Feat : 냥이 목록 초기 화면 & 튜토리얼 버튼 추가
  public/assets/icons/icon-logo-gray.svg
  public/assets/icons/icon-manual.svg
  public/favicon.ico
  src/app/App.tsx
  src/components/mapTemplate/MapTemplate.tsx
  src/components/menuBoard/MenuBoard.tsx
  src/components/searchInpBox/SearchInpBox.tsx
  src/components/tutorialButton/TutorialBtn.tsx
  src/components/tutorialButton/style.ts
  src/pages/catListPage/CatListPage.tsx
  src/pages/catListPage/style.ts
  src/pages/recordMapPage/RecordMapPage.tsx
  src/styles/commonStyle.ts
Labels: feature

#182 Feat/profile edit
  src/components/menuBoard/MenuBoard.tsx
  src/pages/catLetterPage/CatLetterPage.tsx
  src/pages/profileEditPage/ProfileEditPage.tsx
  src/pages/profilePage/ProfilePage.tsx
  src/pages/profilePage/style.ts
Labels: bug

#184 :lipstick: Modify : 전체 스타일 수정
  src/components/catLettersItem/style.ts
  src/components/mapTemplate/style.ts
  src/components/menuBoard/MenuBoard.tsx
  src/components/menuBoard/style.ts
  src/components/modal/deleteModal/style.ts
  src/components/modal/mapModal/style.ts
  src/components/modal/style.ts
  src/components/searchInpBox/style.ts
  src/components/tutorialButton/TutorialBtn.tsx
  src/components/tutorialButton/style.ts
  src/pages/catLetterPage/CatLetterPage.tsx
  src/pages/catLetterPage/style.ts
  src/pages/catListPage/style.ts
  src/pages/recordMapPage/RecordMapPage.tsx
  src/pages/recordMapPage/style.ts
  src/styles/commonStyle.ts
Labels: feature, style

#188 :sparkles: Feat : 반응형 페이지 구현
  public/assets/icons/icon-close-text.svg
  public/assets/images/mobile-tutorial.png
  src/components/mapTemplate/style.ts
  src/components/menuBoard/MenuBoard.tsx
  src/components/menuBoard/style.ts
  src/components/modal/deleteModal/style.ts
  src/components/modal/style.ts
  src/components/searchInpBox/style.ts
  src/components/tutorial/appTutorial/AppTutorial.tsx
  src/components/tutorial/appTutorial/style.ts
  src/components/tutorial/style.ts
  src/components/tutorialButton/style.ts
  src/pages/loginPage/style.ts
  src/pages/recordMapPage/RecordMapPage.tsx
  src/pages/recordMapPage/style.ts
  src/styles/commonStyle.ts
Labels: feature

#189 :lipstick: Modify : UI 수정
  src/atoms/dropdown/style.ts
  src/components/catFeed/CatFeed.tsx
  src/components/catFeed/feedCard/FeedCard.tsx
  src/components/catInfo/CatInfo.tsx
  src/components/home/Home.tsx
  src/components/home/style.ts
  src/components/joinQuizPage/JoinQuizPage.tsx
  src/components/letterBox/LetterBox.tsx
  src/components/letterBox/style.ts
  src/components/loading/style.ts
  src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
  src/components/modal/catFoodPageModal/style.ts
  src/components/modal/catModal/CatModal.tsx
  src/components/modal/deleteModal/DeleteModal.tsx
  src/components/modal/deleteModal/style.ts
  src/components/modal/termsModal/TermsModal.tsx
  src/components/modal/termsModal/style.ts
  src/pages/catInfoEditPage/style.ts
  src/pages/catInfoPage/CatInfoPage.tsx
  src/pages/catListPage/CatListPage.tsx
  src/pages/registerCatPage/RegisterCatPage.tsx
Labels: etc, style

#191 :art: Modify : 이미지 alt 값 생성
  src/components/tutorial/Tutorial.tsx
  src/components/tutorial/appTutorial/AppTutorial.tsx
  src/components/tutorialButton/TutorialBtn.tsx
  src/pages/catListPage/CatListPage.tsx
  src/pages/recordMapPage/RecordMapPage.tsx
  src/styles/commonStyle.ts
Labels: etc, page

#193 🐛 냥이 정보 특이사항 placeholder , 스타일 수정
  src/pages/loginPage/style.ts
  src/pages/registerCatPage/RegisterCatPage.tsx
  src/pages/registerCatPage/style.ts
Labels: bug, style

#195 :lipstick: Modify : 밥정보 리스트 오류 수정
  src/components/catFeed/CatFeed.tsx
  src/pages/catInfoPage/CatInfoPage.tsx
Labels: bug, feature
